services:
  ngnix:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports: 
      - "80:80"
    depends_on:
      - node-app

  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-db:/data/db
    
  redis:
    image: redis

  spaassp-server:
    build:
      context: ./spaasspserver
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    
  python-course:
    build:
      context: ./pythoncourse
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      - FLASK_SERVER_PORT=5050
      - SCRIPT_NAME=/python-course
    
volumes:
  mongo-db:
