services:
  ngnix:
    image: nginx
    ports: 
      - "80:80"
    volumes:
      - ./ngnix/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-db:/data/db
    
  redis:
    image: redis

  spaassp-server:
    build:
      context: ./spaasspserver
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    
volumes:
  mongo-db:
