import express from "express"
import { MongoClient, ObjectId } from "mongodb";
import { MONGO_USER, MONGO_PASSWORD, MONGO_IP, MONGO_PORT } from "./config/config.js";
import { helloServer, getJane, getAllDoctors, createDoctor, login } from "./mongodb/controllers/doctorsController.js"
import { autoGenerateDoctor } from "./utils/randomString.js"

const app = express()
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

const uri = `mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_IP}:${MONGO_PORT}?authSource=admin&retryWrites=true&writeConcern=majority`
const client = new MongoClient(uri);
let testDoctor = autoGenerateDoctor()

app.get("/", () => helloServer(client).catch(console.dir))
app.get("/api/doctors", (req, res) => getAllDoctors(client, req, res))
app.post("/api/testDoctor", (req, res) => createDoctor(client, testDoctor, req, res).catch(console.dir))
app.post("/api/login/", (req, res) => login(req, res, client).catch(console.dir))

const port = process.env.PORT || 3000

app.listen(port, () => console.log(`listening on port ${port}`))

